Add ObjectEncoding command to JedisCluster
redis/jedis pull request #2150
Opened 2020-02-24 14:18 UTC by MichalCho

Added a command mentioned in #2099

2021-01-05 19:38 UTC, gkorland requested changes

2021-01-05 19:38 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/ClusterAdvancedJedisCommandsTest.java
> +
```suggestion
     assertNull(jedisCluster.objectEncoding("myKey")); 
```

2021-01-05 19:38 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/ClusterAdvancedJedisCommandsTest.java
> +  private HostAndPort nodeInfo3 = HostAndPortUtil.getClusterServers().get(2);
```suggestion
  private final HostAndPort nodeInfo1 = HostAndPortUtil.getClusterServers().get(0);
  private final HostAndPort nodeInfo2 = HostAndPortUtil.getClusterServers().get(1);
  private final HostAndPort nodeInfo3 = HostAndPortUtil.getClusterServers().get(2);
```

2021-01-05 19:38 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/ClusterAdvancedJedisCommandsTest.java
> +  JedisCluster jedisCluster;
```suggestion
  private JedisCluster jedisCluster;
```

2021-01-05 19:38 UTC, gkorland commented on src/main/java/redis/clients/jedis/commands/AdvancedClusterCommands.java
> +import java.util.List;
```suggestion
```

2021-01-05 19:38 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/ClusterAdvancedJedisCommandsTest.java
> +import static org.junit.Assert.assertEquals;
```suggestion
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
```

2021-01-05 19:38 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/ClusterAdvancedJedisCommandsTest.java
> +  private static Jedis node3;
```suggestion
  private Jedis node2;
  private Jedis node3;
```

2021-12-08 11:51 UTC, sazzad16 commented
Closed by https://github.com/redis/jedis/commit/858c8051301854e8343eef66aa68c6b9dab1c328

2021-12-08 11:51 UTC, closed without merging