Added Automatic-Module-Name to manifest
redis/jedis pull request #2201
Opened 2020-06-04 10:21 UTC by scholzi100

This PR added the Automatic-Module-Name ("redis.clients.jedis") to the projects manifest.

This PR is related to Issue #2044. 

Compile dependencies supporting Java Module System:
- SLF4J - yes
- commons-pool - [Issue 33](https://github.com/apache/commons-pool/pull/31 )

2020-06-04 10:29 UTC, scholzi100 commented
@sazzad16 can you please review this PR. :grimacing:

2020-07-26 05:15 UTC, wangminpku commented
Dear  scholzi100 ( @scholzi100) and Jedis team  (@xetorthio), (@HeartSaVioR), (@sazzad16 )
We are working on automatically identifying  and clustering the related pull requests for code review. We have found that [PR#1909](https://github.com/xetorthio/jedis/pull/1909) might be related to this one, because both of them modified pom.xml in the same section. 
We would really appreciate it if you could help us to validate if the information from [PR#1909](https://github.com/xetorthio/jedis/pull/1909) is helpful when you review the current PR. 
Thank you very much for your time!

2020-11-23 20:39 UTC, scholzi100 commented
@wangminpku PR#1909 does not seam to be related to this PR.

2021-02-07 12:10 UTC, gkorland commented
@scholzi100 is there a way to test it, to verify the build process?

2021-02-14 18:51 UTC, scholzi100 commented
@gkorland To verify the module is working. I think a seperate module using java 11 with module-info would be required.

2021-03-09 11:17 UTC, sazzad16 commented
@scholzi100 Would you be able to add the module name `redis.clients.jedis` as property and use that property in `Automatic-Module-Name` tag? Thanks!

2021-03-11 16:07 UTC, sazzad16 requested changes
property tags don't match

2021-03-11 16:16 UTC, sazzad16 requested changes

2021-03-11 16:16 UTC, sazzad16 commented on pom.xml
> +		<module.name>redis.clients.jedis</module.name>
```suggestion
		<jedis.module.name>redis.clients.jedis</jedis.module.name>
```

2021-03-11 16:16 UTC, sazzad16 commented on pom.xml
> +							<Automatic-Module-Name>${module.name}</Automatic-Module-Name>
```suggestion
							<Automatic-Module-Name>${jedis.module.name}</Automatic-Module-Name>
```

2021-03-11 16:28 UTC, sazzad16 approved these changes

2021-03-18 08:33 UTC, gkorland approved these changes

2021-03-18 08:53 UTC, merged