Make `getConnection` abstract methods public
redis/jedis pull request #2203
Opened 2020-06-06 01:01 UTC by jchambers

Because the `getConnection` methods in `JedisClusterConnectionHandler` are package-private, they can only be implemented by classes inside the `redis.clients.jedis` package, and the prevents third parties from subclassing `JedisClusterConnectionHandler`.

Third parties may want to subclass `JedisClusterConnectionHandler` and related classes to add things like metrics or fault-tolerance measures. Making these methods public allows them to do so.

2021-01-17 12:51 UTC, sazzad16 commented
@jchambers according to your statement, `protected` should be enough.

2021-01-17 12:52 UTC, sazzad16 requested changes
according to the statement, `protected` should be enough

2021-02-07 12:07 UTC, gkorland approved these changes

2021-02-07 12:26 UTC, sazzad16 approved these changes

2021-02-07 12:31 UTC, merged