Add toString method to the Params class
redis/jedis pull request #2231
Opened 2020-08-24 05:06 UTC by tgrall

* As I am looking at CSC implementation I think it is interesting to add this method.
* I have not added any test as it is very basic  update, let me know if I need to

2020-08-24 05:56 UTC, sazzad16 reviewed
Params may contain `byte[]`. This solution does not handle this.

2020-08-27 06:33 UTC, tgrall commented
@sazzad16 thanks for your review.

I have updated the PR with the following:

* replace the simple Map.toString() using a List (that is closer to how params are used by applications)
* manage `byte[]` 
* add a simple test

2020-08-27 13:24 UTC, sazzad16 requested changes

2020-08-27 13:24 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/params/Params.java
> +            paramsAsString.add(value.toString());
I think `paramsAsString.add(value);` is enough. Later `paramsAsString.toString();` will handle `value.toString()` anyway.

2021-03-09 15:47 UTC, sazzad16 approved these changes

2021-03-09 15:48 UTC, merged