Add support JUSTID flag to XCLAIM command
redis/jedis pull request #2428
Opened 2021-03-13 15:32 UTC by dengliming

Resolves [https://github.com/redis/jedis/issues/2146](https://github.com/redis/jedis/issues/2146)

2021-03-14 16:11 UTC, sazzad16 requested changes
1. Use full `JUSTID` in method name.
2. It is possible to have a version without JUSTID but with XClaimParams.

2021-03-14 16:11 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/PipelineBase.java
> +                                      final String... args) {
```suggestion
      final String... args) {
```

2021-03-14 16:11 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/JedisCommands.java
> +      XClaimParams params, StreamEntryID... ids);
```suggestion
  /**
   *  XCLAIM <key> <group> <consumer> <min-idle-time> <ID-1> <ID-2> ... <ID-N>
   *        [IDLE <milliseconds>] [TIME <mstime>] [RETRYCOUNT <count>]
   *        [FORCE]
   */
  List<StreamEntry> xclaim(String key, String group, String consumername, long minIdleTime,
      XClaimParams params, StreamEntryID... ids);

    /**
   *  XCLAIM <key> <group> <consumer> <min-idle-time> <ID-1> <ID-2> ... <ID-N>
   *        [IDLE <milliseconds>] [TIME <mstime>] [RETRYCOUNT <count>]
   *        [FORCE] JUSTID
   */
  List<StreamEntryID> xclaimJustid(String key, String group, String consumername, long minIdleTime,
      XClaimParams params, StreamEntryID... ids);
```

2021-03-14 17:16 UTC, dengliming commented
> It is possible to have a version without JUSTID but with XClaimParams.

@sazzad16 That make sense to me. Maybe I can do this in a separate pr?

2021-03-14 19:46 UTC, sazzad16 commented
> Maybe I can do this in a separate pr?

If you're more comfortable that way, then sure!

2021-03-14 19:47 UTC, sazzad16 commented
> Maybe I can do this in a separate pr?

@dengliming If you're more comfortable that way, then sure!

2021-03-16 04:57 UTC, sazzad16 requested changes

2021-03-16 04:57 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryClient.java
> +      XClaimParams params, byte[][] ids) {
```suggestion
      XClaimParams params, byte[]... ids) {
```

2021-03-16 04:57 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryClient.java
> +      XClaimParams params, byte[][] ids) {
```suggestion
      XClaimParams params, byte[]... ids) {
```

2021-03-16 04:57 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/JedisCommands.java
> +   *  XCLAIM <key> <group> <consumer> <min-idle-time> <ID-1> <ID-2>
```suggestion
   *  XCLAIM <key> <group> <consumer> <min-idle-time> <ID-1> ... <ID-N>
```

2021-03-16 04:57 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/JedisCommands.java
> +   *  XCLAIM <key> <group> <consumer> <min-idle-time> <ID-1> <ID-2>
```suggestion
   *  XCLAIM <key> <group> <consumer> <min-idle-time> <ID-1> ... <ID-N>
```

2021-03-16 05:05 UTC, merged