Add support for ZDIFF command
redis/jedis pull request #2459
Opened 2021-03-18 14:36 UTC by dengliming

2021-03-18 14:53 UTC, sazzad16 requested changes

2021-03-18 14:53 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryClient.java
> +    sendCommand(ZDIFF, joinParameters(toByteArray(keys.length), keys));
```suggestion
    sendCommand(ZDIFF, toByteArray(keys.length), keys);
```

2021-03-18 14:53 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
> +    assertEquals("b", actual.iterator().next());
```suggestion
    assertEquals(Collections.singleton("b"), jedis.zdiff("foo", "bar"));
```

2021-03-18 14:53 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
> +    assertEquals(new Tuple("b", 2.0d), actualWithScore.iterator().next());
```suggestion
    assertEquals(Collections.singleton(new Tuple("b", 2.0d)), jedis.zdiffWithScores("foo", "bar"));
```

2021-03-18 14:56 UTC, dengliming commented on src/main/java/redis/clients/jedis/BinaryClient.java
> +    sendCommand(ZDIFF, joinParameters(toByteArray(keys.length), keys));
Can't do in this way. : )

2021-03-19 05:29 UTC, sazzad16 approved these changes

2021-03-19 05:38 UTC, merged