Change nil to null in doc
redis/jedis pull request #2524
Opened 2021-04-25 09:36 UTC by einverne

ref #2332

2021-04-25 15:47 UTC, dengliming requested changes

2021-04-25 15:47 UTC, dengliming commented on src/main/java/redis/clients/jedis/BinaryJedis.java
> +   * String, a 'null value is returned instead of the value of the specified key, but the operation
I think both are fine. According to the [redis doc](https://redis.io/commands/mget). It should be `nil`. In java, `null` is also make senses. BTW, `'null` should be `'null'`

2021-04-25 16:05 UTC, sazzad16 commented
@dengliming I object to this change. FYI https://github.com/redis/jedis/pull/2268#issuecomment-766351904

2021-04-26 00:58 UTC, einverne commented
> @dengliming I object to this change. FYI [#2268 (comment)](https://github.com/redis/jedis/pull/2268#issuecomment-766351904)

Oh, sorry, I misunderstand your intention in #2332, I believe we just need one place to explain this clearly. It's not necessary to update the doc everywhere in the codes. So I will close the PR.

2021-04-26 00:58 UTC, closed without merging

2021-04-27 10:50 UTC, sazzad16 commented
@einverne There is nothing to be sorry about. And you did not misunderstand. During #2332, I was not against using `null`. But as I was thinking about #2332 and #2268, I was preferring `nil` more and more.

2024-08-10 14:16 UTC, devxzero commented
'nil' is just plain wrong from a Java perspective. And since this is Java language, it it should be documented as null.
A lot of people who are experienced with Java, but new to Redis, will get a nullpointerexception, and wonder: _why is it returning null, the doc says "the special value 'nil' is returned"_ The 'nil' is even between quotes, which suggests that it should be taken literary as a literal string. Yes, I did wonder: why didn't they return just null? I thought, maybe Jedis wants to stick as low level as possible, so it doesn't want to translate 'nil' to null.
It causes people who are new to Redis to have to debug the Jedis code to understand why this problem exists. After some googling, I found multiple issues about this problem on this repo.

2024-08-11 15:50 UTC, sazzad16 commented
@devxzero or anyone else interested, would you like to craft a PR? The PR should cover all 'nil' (as much as possible) and use more modern javadoc styles (e.g. `{@code null}`).