Return type should be 'long' (or any primitive)
redis/jedis pull request #2547
Opened 2021-05-17 07:47 UTC by sazzad16

Resolves #2543

2021-05-17 15:02 UTC, dengliming approved these changes

2021-05-18 11:46 UTC, mina-asham approved these changes
Due to the size of the review I was mostly sampling here, as far as I can see and notice this is fine :)

One comment though, this can target an earlier release than 4.0.0, this change is backward compatible (going from wrapper primitives to primitives is a backward compatible change in general, the other way is the one that might be incompatible in some cases)

2021-05-18 12:43 UTC, sazzad16 commented
> this can target an earlier release than 4.0.0, this change is backward compatible (going from wrapper primitives to primitives is a backward compatible change in general, the other way is the one that might be incompatible in some cases)

@mina-asham I'm okay with it. But others may not agree.

I chose 4.0.0 as a safer option so that existing `jedis.xlen("xlen-stream").longValue()` kind of codes don't get broken when updated.

@gkorland ping!

2021-05-18 14:12 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryJedis.java
> -   * Object class has implemented "wait" method, we cannot use it, so I had to change the name of
@gkorland The interface, BasicCommands, has better JDoc https://github.com/redis/jedis/pull/2547/files#diff-d54b47364c0fa44a622800fecc2a8edf5723746cf27feae7d136ba7357701d03R202-R216

2021-05-18 14:16 UTC, gkorland requested changes

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/PipeliningTest.java
> +    assertEquals(5, jedis.incrBy(key, 5L));
```suggestion
    assertEquals(5L, jedis.incrBy(key, 5L));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(1, jedis.del("foo"));
```suggestion
    assertEquals(1L, jedis.del("foo"));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(1, jedis.del(bfoo));
```suggestion
    assertEquals(1L, jedis.del(bfoo));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(2, jedis.exists("foo1", "foo2"));
```suggestion
    assertEquals(2L, jedis.exists("foo1", "foo2"));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(1, jedis.del("foo1"));
```suggestion
    assertEquals(1L, jedis.del("foo1"));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(1, jedis.exists("foo1", "foo2"));
```suggestion
    assertEquals(1L, jedis.exists("foo1", "foo2"));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(3, jedis.del("foo1", "foo2", "foo3"));
```suggestion
    assertEquals(3L, jedis.del("foo1", "foo2", "foo3"));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(1, jedis.del("foo1", "foo2"));
```suggestion
    assertEquals(1L, jedis.del("foo1", "foo2"));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(0, jedis.del("foo1", "foo2"));
```suggestion
    assertEquals(0L, jedis.del("foo1", "foo2"));
```

2021-05-18 14:16 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
> +    assertEquals(3, jedis.del(bfoo1, bfoo2, bfoo3));
```suggestion
    assertEquals(3L, jedis.del(bfoo1, bfoo2, bfoo3));
```

2021-05-18 14:20 UTC, gkorland requested changes

2021-05-18 14:20 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/BinaryValuesCommandsTest.java
> +    assertEquals("OK", jedis.set(bfoo, bbar));
```suggestion
    assertEquals(Keyword.OK.name(), jedis.set(bfoo, bbar));
```

2021-05-18 14:20 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/BinaryValuesCommandsTest.java
> +    assertEquals(-1, jedis.ttl(bfoo));
```suggestion
    assertEquals(-1L, jedis.ttl(bfoo));
```

2021-05-18 14:23 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/StringValuesCommandsTest.java
>      assertEquals(1L + Integer.MAX_VALUE, (long) jedis.incrBy("foo", Integer.MAX_VALUE));
```suggestion
    assertEquals(1L + Integer.MAX_VALUE, jedis.incrBy("foo", Integer.MAX_VALUE));
```

2021-05-18 14:24 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
> +    assertEquals(1, jedis.xlen("xadd-stream3"));
```suggestion
    assertEquals(1L, jedis.xlen("xadd-stream3"));
```

2021-05-18 14:24 UTC, gkorland commented on src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
> +    assertEquals(0, jedis.xlen("xadd-stream3"));
```suggestion
    assertEquals(0L, jedis.xlen("xadd-stream3"));
```

2021-05-18 15:29 UTC, gkorland approved these changes

2021-05-18 15:53 UTC, merged