Support GEOSEARCH and GEOSEARCHSTORE commands
redis/jedis pull request #2677
Opened 2021-10-25 11:11 UTC by AvitalFineRedis

Support GEOSEARCH and GEOSEARCHSTORE commands.
Also created GeoSearchParam class to support all the params for both commands.

2021-11-01 10:46 UTC, sazzad16 commented
@yangbodong22011 @dengliming @gkorland @mina-asham 

Should we name `geosearch` or `geoSearch`?

2021-11-01 10:51 UTC, yangbodong22011 commented
> @yangbodong22011 @dengliming @gkorland @mina-asham
> 
> Should we name `geosearch` or `geoSearch`?

If you follow the old style (georadius, georadiusStore), it should be:
`geosearch`  
`geosearchStore`

2021-11-01 12:13 UTC, sazzad16 commented
Also, what about the name of method for `geosearchstore` with `storedist`?

- `geosearchStoreStoreDist` - according to Redis doc (and existing pattern)
- `geosearchStoreDist` - alters existing pattern
- `geosearchStoreWithDist` - meaningful but doesn't match Redis doc

2021-11-01 15:12 UTC, yangbodong22011 commented
> Also, what about the name of method for `geosearchstore` with `storedist`?
> 
> * `geosearchStoreStoreDist` - according to Redis doc (and existing pattern)
> * `geosearchStoreDist` - alters existing pattern
> * `geosearchStoreWithDist` - meaningful but doesn't match Redis doc

🤣 i vote for `geosearchStoreStoreDist `

2021-11-02 12:52 UTC, sazzad16 submitted a review, later dismissed

2021-11-02 13:00 UTC, sazzad16 requested changes
Please use

- `geosearchStore`
- `geosearchStoreStoreDist`

in proper places.

Also, separate `GeoRadiusParam` and `GeoSearchParam`. There would be some codes twice but, IMO, it's a better trade off compared to introducing new patterns.

2021-11-04 01:54 UTC, yangbodong22011 reviewed
It seems that there is a lack of adding corresponding commands in `MultiKeyPipelineBase.java` and `PipelineBase.java`

2021-11-04 09:08 UTC, yangbodong22011 commented on src/main/java/redis/clients/jedis/MultiKeyPipelineBase.java
> +  public Response<Long> geosearchStore(String dest, String src, String member, double radius, GeoUnit unit) {
need add
```
public void geosearchStore(byte[] dest, byte[] src, byte[] member, double radius, GeoUnit unit)
```

in pipeline, binary command and string command are in same file.

2021-11-04 10:57 UTC, yangbodong22011 commented on src/main/java/redis/clients/jedis/BinaryJedisCluster.java
> +    }.runBinary(src);}
`} `Need to wrap...The following three methods are also.

2021-11-04 12:22 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryJedisCluster.java
> +    }.runBinary(src);}
```suggestion
    }.runBinary(src);
  }
```

2021-11-04 12:22 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryJedisCluster.java
> +    }.runBinary(src);}
```suggestion
    }.runBinary(src);
  }
```

2021-11-04 12:22 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryJedisCluster.java
> +    }.runBinary(src);}
```suggestion
    }.runBinary(src);
  }
```

2021-11-04 12:22 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BinaryJedisCluster.java
> +    }.runBinary(src);}
```suggestion
    }.runBinary(src);
  }
```

2021-11-04 12:22 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/JedisCluster.java
> +    }.run(src);  }
```suggestion
    }.run(src);
  }
```

2021-11-04 12:28 UTC, sazzad16 requested changes
For MultiKey commands (geosearchStore...), `.run(src);` -> `.run(2, dest, src);`.
Similar for binary commands.

2021-11-04 13:12 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/JedisCluster.java
> +    }.run(2, dest, src);  }
```suggestion
    }.run(2, dest, src);
  }
```

2021-11-04 13:14 UTC, sazzad16 approved these changes

2021-11-04 13:30 UTC, yangbodong22011 approved these changes

2021-11-06 16:22 UTC, dengliming approved these changes

2021-12-31 14:10 UTC, closed without merging