Support Json Commands
redis/jedis pull request #2681
Opened 2021-11-01 12:04 UTC by AvitalFineRedis

2021-11-01 12:16 UTC, sazzad16 requested changes

2021-11-01 12:16 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/json/RedisJsonCommands.java
> +  String jsonSet(String key, Object object, ExistenceModifier flag, Path path);
Replace ExistenceModifier with an IParams (and name it properly).

2021-11-01 15:30 UTC, sazzad16 requested changes

2021-11-01 15:30 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BuilderFactory.java
> +  public static final Builder<Class<?>> CLASS = new Builder<Class<?>>() {
1. rename it more descriptive and unique; i.e. REDIS_JSON_TYPE
2. move it after all core Redis related builders; i.e. after STR_ALGO_LCS_RESULT

2021-11-02 13:10 UTC, merged

2021-11-08 07:44 UTC, yangbodong22011 commented
I don’t think it’s a good way to add the Module command directly into the Jedis code. It has the following disadvantages:

- With more and more Redis Modules, adding or modifying module commands may require a Jedis release.
- It is difficult to decide which Module commands need to be supported by Jedis, whether they are driven by the community PR or the Maintainer.

Some of my possible suggestions:
- A plug-in mechanism that allows the community to implement different Module commands by itself. `Jedis + different Module pom` can support different Modules, so as to avoid the modification of RedisJSON, which will cause a passive release of RedisSearch.

2021-11-15 11:36 UTC, chayim commented
@yangbodong22011 Interesting! There's another pattern we can consider to properly support this option.  What if there was a loader that made it easy to include (possibly via reflection, ugz) different modules. This could solve that, and we could still go down this path...