support jedis migrate keys encoded by gdk failed
redis/jedis pull request #2689
Opened 2021-11-13 02:49 UTC by zeekling

### Expected behavior

use `migrate` function migrate value success when the key contains china string encoded by gbk.

### Actual behavior

use `migrate` function migrate value failed when the key contains china strings encoded by gbk.

### Steps to reproduce:

1. write china strings encoded by gdb use hiredis.
2. use `clusterGetKeysInSlot` get all keys in slot.
3. migrate keys to other node. its failed due to jedis decode strings by utf-8.

### Redis / Jedis Configuration

#### Jedis version:2.8.2

#### Redis version:5.0.4

#### Java version:1.8

issus: https://github.com/redis/jedis/issues/2688

2021-11-13 07:34 UTC, sazzad16 requested changes
Rename the method to `clusterGetKeysInSlotBinary`.

2021-11-14 04:57 UTC, zeekling commented
> Rename the method to `clusterGetKeysInSlotBinary`.

done!

2021-11-14 06:01 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/tests/commands/ClusterCommandsTest.java
> +  public void clusterGetByteKeysInSlot() {
```suggestion
  public void clusterGetKeysInSlotBinary() {
```

2021-11-14 06:02 UTC, sazzad16 approved these changes

2021-11-30 06:42 UTC, zeekling commented
pls merge @sazzad16

2021-12-04 11:44 UTC, sazzad16 approved these changes

2021-12-04 11:45 UTC, merged