Replace old interface with new interface of JedisPoolConfig
redis/jedis pull request #2749
Opened 2021-12-17 15:13 UTC by zeekling

setMinEvictableIdleTimeMillis replaced with setMinEvictableIdleTime

```java
 /**
     * Sets the value for the {@code minEvictableIdleTime} configuration
     * attribute for pools created with this configuration instance.
     *
     * @param minEvictableIdleTimeMillis The new setting of
     *        {@code minEvictableIdleTime} for this configuration instance
     *
     * @see GenericObjectPool#getMinEvictableIdleDuration()
     * @see GenericKeyedObjectPool#getMinEvictableIdleDuration()
     * @deprecated Use {@link #setMinEvictableIdleTime(Duration)}.
     */
    @Deprecated
    public void setMinEvictableIdleTimeMillis(final long minEvictableIdleTimeMillis) {
        this.minEvictableIdleDuration = Duration.ofMillis(minEvictableIdleTimeMillis);
    }
```

setTimeBetweenEvictionRunsMillis replaced with setTimeBetweenEvictionRuns

```java
 /**
     * Sets the value for the {@code timeBetweenEvictionRuns} configuration
     * attribute for pools created with this configuration instance.
     *
     * @param timeBetweenEvictionRunsMillis The new setting of
     *        {@code timeBetweenEvictionRuns} for this configuration
     *        instance
     *
     * @see GenericObjectPool#getDurationBetweenEvictionRuns()
     * @see GenericKeyedObjectPool#getDurationBetweenEvictionRuns()
     * @deprecated Use {@link #setTimeBetweenEvictionRuns(Duration)}.
     */
    @Deprecated
    public void setTimeBetweenEvictionRunsMillis(final long timeBetweenEvictionRunsMillis) {
        setTimeBetweenEvictionRuns(Duration.ofMillis(timeBetweenEvictionRunsMillis));
    }
```

2021-12-17 15:54 UTC, sazzad16 requested changes
Please make similar changes to ConnectionPoolConfig.

2021-12-18 01:37 UTC, zeekling commented
> Please make similar changes to ConnectionPoolConfig.

done!

2021-12-19 05:51 UTC, sazzad16 requested changes
Nit-picky. Put java... imports before org... imports.

2021-12-19 06:27 UTC, sazzad16 approved these changes

2021-12-19 06:28 UTC, merged