ACL patterns for Pub/Sub channels
redis/jedis pull request #2750
Opened 2021-12-18 05:35 UTC by zeekling

ACL patterns for Pub/Sub channels

return result:
```
> ACL GETUSER default
1) "flags"
2) 1) "on"
   2) "allkeys"
   3) "allcommands"
   4) "nopass"
3) "passwords"
4) (empty array)
5) "commands"
6) "+@all"
7) "keys"
8) 1) "*"
9) "channels"
10) 1) "*"
```

2021-12-19 06:27 UTC, sazzad16 requested changes

2021-12-19 06:27 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/resps/AccessControlUser.java
> +        + ", channels='" + channels + ", commands='" + commands + '\'' + '}';
put channels after commands

2021-12-19 06:27 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/commands/jedis/AccessControlListCommandsTest.java
> +    assertEquals(userInfo.getChannels().get(0), "testchannel:*");
should be expected first and actual later
```suggestion
    assertEquals("testchannel:*", userInfo.getChannels().get(0));
```

2021-12-29 11:16 UTC, zeekling commented on src/main/java/redis/clients/jedis/resps/AccessControlUser.java
> +        + ", channels='" + channels + ", commands='" + commands + '\'' + '}';
done

2022-01-18 14:30 UTC, sazzad16 requested changes

2022-01-18 14:30 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/AccessControlLogBinaryCommands.java
> +   * @see <a href="https://redis.io/commands/acl-getuser">ACL GETUSER username</a>
Remove `@see` tag.
Add the link in description.

2022-01-18 14:30 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/AccessControlLogCommands.java
> +   * @see <a href="https://redis.io/commands/acl-getuser">ACL GETUSER username</a>
Remove `@see` tag.
Add the link in description.

2022-01-18 14:30 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BuilderFactory.java
> +      }
Use less return statements.
```suggestion
      // before redis 6.2, no channels info
      if (objectList.size() > 9) {
        List<Object> channels = objectList.get(9);
        for (Object channel : channels) {
          accessControlUser.addChannel(SafeEncoder.encode((byte[]) channel));
        }
      }
```

2022-01-18 14:43 UTC, dengliming commented on src/main/java/redis/clients/jedis/resps/AccessControlUser.java
> +  public void addChannel(String channel){
```suggestion
  public void addChannel(String channel) {
```
formmat code

2022-01-19 06:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/AccessControlLogBinaryCommands.java
> +   * @see <a href="https://redis.io/commands/acl-getuser">ACL GETUSER username</a>
```suggestion
```

2022-01-19 06:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/AccessControlLogCommands.java
> +   * @see <a href="https://redis.io/commands/acl-getuser">ACL GETUSER username</a>
```suggestion
```

2022-01-19 06:28 UTC, merged