Added the BYTE|BIT option for bitcount
redis/jedis pull request #2768
Opened 2021-12-26 08:35 UTC by zeekling

Added the BYTE|BIT option for bitcount

![image](https://user-images.githubusercontent.com/17929800/147403045-15389467-8c92-4377-aa30-440dbab086e0.png)

2021-12-26 10:55 UTC, sazzad16 reviewed
Return type for both bitcountByte and bitcountBit is same. IMO, it's better to create a BitCountOption in `args` package and just do `bitcount(key, start, end, bitcountOption)`.

2021-12-26 13:02 UTC, zeekling commented
done

2021-12-26 13:12 UTC, sazzad16 requested changes
Also, add `bitcount(String key, long start, long end, BitCountOption option)` variants.

2021-12-26 13:12 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +    return new CommandObject<>(commandArguments(BITCOUNT).key(key).add(start).add(end).add(option.getRaw()), BuilderFactory.LONG);
```suggestion
    return new CommandObject<>(commandArguments(BITCOUNT).key(key).add(start).add(end).add(option), BuilderFactory.LONG);
```

2021-12-27 03:11 UTC, yangbodong22011 approved these changes

2021-12-27 16:01 UTC, zeekling commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +    return new CommandObject<>(commandArguments(BITCOUNT).key(key).add(start).add(end).add(option.getRaw()), BuilderFactory.LONG);
done

2021-12-28 06:37 UTC, sazzad16 approved these changes

2021-12-28 06:37 UTC, merged