Support REPLICAOF Command
redis/jedis pull request #2811
Opened 2022-01-11 11:40 UTC by AvitalFineRedis

[REPLICAOF](https://redis.io/commands/replicaof)

2022-01-11 13:58 UTC, sazzad16 requested changes
Please deprecate SLAVEOF commands.
You can check #2673 for idea.

Also, put the new methods just after those.

2022-01-11 17:54 UTC, sazzad16 requested changes

2022-01-11 17:54 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +  @Deprecated
add suggestion in javadoc

2022-01-11 17:54 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +  @Deprecated
add suggestion in javadoc

2022-01-12 01:01 UTC, sazzad16 approved these changes

2022-01-12 02:19 UTC, yangbodong22011 approved these changes

2022-01-12 07:10 UTC, merged