Add javadoc to interfaces
redis/jedis pull request #2829
Opened 2022-01-18 13:15 UTC by AvitalFineRedis

2022-01-19 10:35 UTC, sazzad16 reviewed
If you're changing the variable names in interfaces (e.g. member -> members, string -> strings, arg -> args), you should also rename those in implemented methods (in classes).

2022-01-20 10:08 UTC, sazzad16 requested changes
1. Don't use `@see` tags for URLs. You can add URLs in description if you want.
2. When using `@see` tag (except above [1]), Clarify how respective method is different from the method in `@see`. (Or, simply avoid `@see` and add whole description.)

2022-01-20 13:45 UTC, zeekling requested changes

2022-01-20 13:45 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/DatabaseCommands.java
> +  String migrate(String host, int port, int destinationDB, int timeout, MigrateParams params,
Please add javadoc for this method

2022-01-20 13:45 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/GeoCommands.java
> +   * @param key
Please add description for params.

2022-01-20 14:21 UTC, sazzad16 requested changes
Please re-check all your `Similar ...`. It would be better to use a method to use as Similar which has actual description.

Also, `Similar...`s are very good place to use `@see` tag.

Furthermore, use full method name. E.g. `KeyCommands#sort(...)` instead of just `#sort(...)`.

2022-01-20 14:21 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/KeyCommands.java
> +   * Similar to {@link KeyCommands#exists(String) EXISTS} with multiple keys.
Elaborate; return type is different. What does the return mean?

2022-01-20 14:21 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
> +   * Similar to {@link SortedSetCommands#zadd(String, Map<String, Double>) ZADD} with optional params.
Method you're referring to does not contain any detail but refers to another one. Don't do that.

2022-01-20 14:21 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
> +   * Similar to {@link SortedSetCommands#zrevrangeByScore(String, double, double) ZREVRANGEBYSCORE} with string range.
```suggestion
   * Similar to {@link SortedSetCommands#zrevrangeByScore(String, double, double) ZREVRANGEBYSCORE} with <i>exclusive</i> range.
```

2022-01-20 14:21 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/ListCommands.java
> +import redis.clients.jedis.args.GeoUnit;
```suggestion
```

2022-01-25 15:37 UTC, Avital-Fine commented
Can be closed due to #2842

2022-01-25 15:51 UTC, closed without merging