Support SORT_RO
redis/jedis pull request #2843
Opened 2022-01-25 16:20 UTC by Avital-Fine

https://redis.io/commands/sort_ro

2022-01-25 16:32 UTC, sazzad16 requested changes

2022-01-25 16:32 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/KeyBinaryCommands.java
> +import redis.clients.jedis.Response;
```suggestion
```

2022-01-25 16:32 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/KeyCommands.java
> +   * <p>
```suggestion
   *
```

2022-01-25 16:32 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/commands/jedis/SortingCommandsTest.java
> +import static org.junit.Assert.assertTrue;
```suggestion
```

2022-01-25 16:32 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/commands/jedis/SortingCommandsTest.java
> +import java.util.Arrays;
```suggestion
```

2022-01-26 02:57 UTC, dengliming approved these changes

2022-01-26 03:08 UTC, sazzad16 approved these changes

2022-01-26 04:38 UTC, merged