Support ZINTERCARD (new Command in Redis7.0.0)
redis/jedis pull request #2844
Opened 2022-01-25 17:08 UTC by Avital-Fine

https://redis.io/commands/zintercard

2022-01-25 18:39 UTC, sazzad16 requested changes
Undo renaming all `keys` to `sets`, conforming redis.io doc.

2022-01-26 12:56 UTC, sazzad16 requested changes
ZINTERCARD numkeys key [key ...] [LIMIT limit] 

@Avital-Fine As long as redis.io using key/keys, we're also using key/keys.

2022-01-26 12:56 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
> +    return appendCommand(commandObjects.zintercard(keys));
```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/circleci/project/src/main/java/redis/clients/jedis/MultiNodePipelineBase.java:[1123,52] cannot find symbol
  symbol:   variable keys
```

2022-01-26 13:28 UTC, zeekling requested changes

2022-01-26 13:28 UTC, zeekling commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +  public final CommandObject<Long> zintercard(String... sets) {
```suggestion
  public final CommandObject<Long> zintercard(String... keys) {
```

2022-01-26 13:28 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
> +  long zintercard(long limit, byte[]... sets);
Please add javadoc for interface.

2022-01-26 13:28 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
> +  long zintercard(long limit, String... sets);
Please add javadoc for interface.

2022-01-26 13:28 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
> +  Response<Long> zintercard(long limit, byte[]... sets);
Please add javadoc for interface.

2022-01-26 13:28 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/SortedSetPipelineCommands.java
> +  Response<Long> zintercard(long limit, String... sets);
Please add javadoc for interface.

2022-01-26 14:20 UTC, sazzad16 requested changes

2022-01-26 14:20 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +            .add(keys.length).keys((Object[]) keys), BuilderFactory.LONG);
```suggestion
    return new CommandObject<>(commandArguments(ZINTERCARD).add(keys.length)
        .keys((Object[]) keys), BuilderFactory.LONG);
```

2022-01-26 14:20 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +            .add(keys.length).keys((Object[]) keys).add(LIMIT).add(limit), BuilderFactory.LONG);
```suggestion
    return new CommandObject<>(commandArguments(ZINTERCARD).add(keys.length)
        .keys((Object[]) keys).add(LIMIT).add(limit), BuilderFactory.LONG);
```

2022-01-26 14:20 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +        .add(keys.length).keys((Object[]) keys), BuilderFactory.LONG);
```suggestion
    return new CommandObject<>(commandArguments(ZINTERCARD).add(keys.length)
        .keys((Object[]) keys), BuilderFactory.LONG);
```

2022-01-26 14:20 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +            .add(keys.length).keys((Object[]) keys).add(LIMIT).add(limit), BuilderFactory.LONG);
```suggestion
    return new CommandObject<>(commandArguments(ZINTERCARD).add(keys.length)
        .keys((Object[]) keys).add(LIMIT).add(limit), BuilderFactory.LONG);
```

2022-01-26 14:20 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Protocol.java
> +    STRALGO, GEOSEARCH, GEOSEARCHSTORE, LOLWUT, REPLICAOF, ZRANGESTORE, SINTERCARD, SORT_RO, ZINTERCARD;
```suggestion
    STRALGO, GEOSEARCH, GEOSEARCHSTORE, LOLWUT, REPLICAOF, ZRANGESTORE, SINTERCARD, ZINTERCARD,
    SORT_RO;
```

2022-01-26 14:30 UTC, sazzad16 approved these changes

2022-01-27 07:43 UTC, sazzad16 approved these changes

2022-01-27 09:19 UTC, dengliming approved these changes

2022-01-27 09:43 UTC, merged