Support LCS
redis/jedis pull request #2855
Opened 2022-01-31 16:05 UTC by Avital-Fine

Add support to new [LCS](https://redis.io/commands/lcs) command, and deprecate STRALGO command

2022-01-31 16:07 UTC, Avital-Fine commented
Can we deprecate strAlgo now that we have LCS? It supposes to be deprecated in Redis 7.0.0

2022-02-01 07:08 UTC, zeekling requested changes

2022-02-01 07:08 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/StringBinaryCommands.java
> +  LCSMatchResult lcs(byte[] keyA, byte[] keyB, LCSParams params);
Add javadoc

2022-02-01 07:08 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/StringPipelineBinaryCommands.java
> +import redis.clients.jedis.params.*;
Do not use `.*` in import

2022-02-01 07:08 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/StringPipelineBinaryCommands.java
> +  Response<LCSMatchResult> lcs(byte[] keyA, byte[] keyB, LCSParams params);
Add javadoc

2022-02-01 07:08 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/StringPipelineCommands.java
> +import redis.clients.jedis.params.*;
Do not use `.*` in import

2022-02-01 07:08 UTC, zeekling commented on src/main/java/redis/clients/jedis/params/LCSParams.java
> +    if (minMatchLen != null) {
```suggestion
    if (minMatchLen != null && minMatchLen >= 0) {
```

2022-02-01 07:15 UTC, sazzad16 commented
> Can we deprecate strAlgo now that we have LCS? It supposes to be deprecated in Redis 7.0.0

@Avital-Fine We absolutely can. You can include those in this PR or do that in a separate PR or simply create an issue :slightly_smiling_face:

2022-02-01 09:17 UTC, Avital-Fine commented
> > Can we deprecate strAlgo now that we have LCS? It supposes to be deprecated in Redis 7.0.0
> 
> @Avital-Fine We absolutely can. You can include those in this PR or do that in a separate PR or simply create an issue slightly_smiling_face

Cool, I'm doing it in this PR

2022-02-01 10:11 UTC, sazzad16 requested changes
AFAIK, `LCS` command is not available before Redis 7. So user can't just start using it. In that case deprecation message can say,

    STRALGO LCS command will be removed from Redis 7. {@link ...} can be used instead of this method.

2022-02-01 10:11 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/params/LCSParams.java
> +    if (minMatchLen != null && minMatchLen >= 0) {
```suggestion
    if (minMatchLen != null) {
```

If anybody wants, let them watch what happens when `minMatchLen < 0`.

2022-02-01 11:34 UTC, sazzad16 requested changes

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/StringCommands.java
> +   * @param params {@link StrAlgoLCSParams}
```suggestion
   * @param keyA
   * @param keyB
   * @param params
```

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/StringCommands.java
> +   * @param params {@link LCSParams}
```suggestion
   * @param keyA
   * @param keyB
   * @param params
```

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/StringBinaryCommands.java
> +   * @param params {@link LCSParams}
```suggestion
   * @param keyA
   * @param keyB
   * @param params
```

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +   * @param params the params
```suggestion
   * @param keyA
   * @param keyB
   * @param params
```

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +   * @param params the params
```suggestion
   * @param keyA
   * @param keyB
   * @param params
```

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +  @Deprecated
```suggestion
  /**
   * @deprecated STRALGO LCS command will be removed from Redis 7.
   */
  @Deprecated
```

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +  @Deprecated
`   * @deprecated STRALGO LCS command will be removed from Redis 7.`

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +            .addParams(params), BuilderFactory.STR_ALGO_LCS_RESULT_BUILDER);
```suggestion
    return new CommandObject<>(commandArguments(Command.LCS).key(keyA).key(keyB)
        .addParams(params), BuilderFactory.STR_ALGO_LCS_RESULT_BUILDER);
```

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Protocol.java
> +    SORT_RO, EVAL_RO, EVALSHA_RO, LCS;
STRALGO can be deprecated.

2022-02-01 11:34 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Protocol.java
> +    ANY, FROMMEMBER, FROMLONLAT, BYRADIUS, BYBOX, BYLEX, BYSCORE, REV, IDX, MINMATCHLEN, WITHMATCHLEN;
LCS and STRINGS can be deprecated.

2022-02-01 12:32 UTC, sazzad16 requested changes
Hopefully last change request in this PR. Deprecate in `src/main/java/redis/clients/jedis/CommandObjects.java`

2022-02-03 13:58 UTC, merged