Support [NX|XX|GT|LT] options in EXPIREAT and PEXPIREAT
redis/jedis pull request #2874
Opened 2022-02-06 14:32 UTC by Avital-Fine

2022-02-06 14:37 UTC, sazzad16 requested changes
Please keep all `At` method together. I.e.

- expireAt(String key, long unixTime);
- expireAt(String key, long unixTime, ExpiryOption expiryOption);
- pexpireAt(String key, long millisecondsTimestamp);
- pexpireAt(String key, long millisecondsTimestamp, ExpiryOption expiryOption);

2022-02-06 15:23 UTC, Avital-Fine commented
> Please keep all `At` method together. I.e.
> 
> * expireAt(String key, long unixTime);
> * expireAt(String key, long unixTime, ExpiryOption expiryOption);
> * pexpireAt(String key, long millisecondsTimestamp);
> * pexpireAt(String key, long millisecondsTimestamp, ExpiryOption expiryOption);

I changed it so now the order of all the expire commands is:

- expire(String key, long seconds);
- expire(String key, long seconds, ExpiryOption expiryOption);
- pexpire(String key, long milliseconds);
- pexpire(String key, long milliseconds, ExpiryOption expiryOption);
- expireTime(String key);
- pexpireTime(String key);
- expireAt(String key, long unixTime);
- expireAt(String key, long unixTime, ExpiryOption expiryOption);
- pexpireAt(String key, long millisecondsTimestamp);
- pexpireAt(String key, long millisecondsTimestamp, ExpiryOption expiryOption);

2022-02-06 15:37 UTC, sazzad16 requested changes
> I changed it so now the order of all the expire commands is:
> ...
> ...

@Avital-Fine You've missed some orderings in Jedis.java and Pipeline.java

2022-02-07 06:55 UTC, sazzad16 approved these changes

2022-02-07 06:56 UTC, merged