Support passing args to MODULE LOAD
redis/jedis pull request #2918
Opened 2022-02-21 11:22 UTC by Avital-Fine

closes #2904

2022-02-21 15:50 UTC, zeekling requested changes

2022-02-21 15:50 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/ModuleCommands.java
> +  String moduleLoad(String path, String... args);
add javadoc

2022-02-21 15:50 UTC, zeekling commented on src/main/java/redis/clients/jedis/Jedis.java
> +    connection.sendCommand(MODULE, newArgs);
```suggestion
    connection.sendCommand(MODULE, joinParameters(LOAD.name(), path, args));
```

2022-02-22 06:23 UTC, sazzad16 requested changes

2022-02-22 06:23 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +    return connection.getStatusCodeReply();  }
```suggestion
    return connection.getStatusCodeReply();
  }
```

2022-02-22 23:54 UTC, sazzad16 approved these changes

2022-02-22 23:55 UTC, merged