Support XGROUP CREATECONSUMER
redis/jedis pull request #2919
Opened 2022-02-21 11:54 UTC by Avital-Fine

Closes #2905

2022-02-21 15:43 UTC, zeekling commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +  public final CommandObject<Long> xgroupCreateConsumer(String key, String groupname, String consumername) {
```suggestion
  public final CommandObject<Long> xgroupCreateConsumer(String key, String groupName, String consumerName) {
```

2022-02-21 15:43 UTC, zeekling commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +  public final CommandObject<Long> xgroupDelConsumer(byte[] key, byte[] groupname, byte[] consumername) {
```suggestion
  public final CommandObject<Long> xgroupDelConsumer(byte[] key, byte[] groupName, byte[] consumerName) {
```

2022-02-21 15:43 UTC, zeekling commented on src/main/java/redis/clients/jedis/commands/StreamBinaryCommands.java
> +  long xgroupCreateConsumer(byte[] key, byte[] groupname, byte[] consumerName);
add javadoc

2022-02-22 06:21 UTC, sazzad16 requested changes

2022-02-22 06:21 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/StreamCommands.java
> +  long xgroupCreateConsumer(String key, String groupname, String consumername);
```suggestion
  boolean xgroupCreateConsumer(String key, String groupname, String consumername);
```

2022-02-22 06:21 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
> +    assertEquals(1L, jedis.xgroupCreateConsumer("xgroup-stream", "consumer-group-name1","myconsumer1"));
Do this after following assert. Also try to delete that consumer (again). You can also consider using a different groupname.

2022-02-22 06:21 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Protocol.java
> +    PURGE, STATS, @Deprecated LCS, @Deprecated STRINGS, CREATECONSUMER;
```suggestion
    PURGE, STATS, CREATECONSUMER, @Deprecated LCS, @Deprecated STRINGS;
```

2022-02-23 07:23 UTC, sazzad16 approved these changes

2022-02-23 07:24 UTC, merged