Support COMMAND [...] commands
redis/jedis pull request #2922
Opened 2022-02-22 19:16 UTC by Avital-Fine

2022-03-05 13:15 UTC, sazzad16 requested changes

2022-03-05 13:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Protocol.java
> +    DOCS, GETKEYS, GETKEYSANDFLAGS, @Deprecated STRALGO;
```suggestion
    LOLWUT, EXPIRETIME, PEXPIRETIME, FUNCTION, FCALL, FCALL_RO, LMPOP, BLMPOP, ZMPOP, BZMPOP,
    COMMAND, DOCS, GETKEYS, GETKEYSANDFLAGS, @Deprecated STRALGO;
```

2022-03-05 13:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +    return connection.getIntegerReply();
```suggestion
    return connection.executeCommand(commandObjects.commandCount());
```

2022-03-05 13:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/resps/KeyedFlags.java
> +public class KeyedFlags {
Remove this. Use `KeyValue<String, List<String>>`.

2022-03-05 13:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/UnifiedJedis.java
> +  public List<CommandDocs> commandDocs(String... commands) {
```suggestion
  public Map<String, CommandDocs> commandDocs(String... commands) {
```

2022-03-05 13:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/CommandCommands.java
> +  List<String> commandListFilterByPattern(String pattern);
We can use a new params class `CommandListFilterByParams`.

2022-03-05 13:15 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/resps/CommandDocs.java
> +public class CommandDocs {
`CommandDocument`?

2022-03-06 16:22 UTC, sazzad16 requested changes

2022-03-06 16:22 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Protocol.java
> +    COMMAND, DOCS, GETKEYS, GETKEYSANDFLAGS, @Deprecated STRALGO;
Only COMMAND is the command here, others are keywords.

2022-03-06 16:22 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/params/CommandListFilterByParams.java
> +  public CommandListFilterByParams filterByAclcat(String category) {
filterByAclCat

2022-03-07 05:33 UTC, sazzad16 requested changes

2022-03-07 05:33 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BuilderFactory.java
> +        }
Create a "single object" builder in CommandDocument class.

2022-03-07 05:33 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/BuilderFactory.java
> +        List<String> subcommands = STRING_LIST.build(commandInfo.get(9));
Create a "single object" builder in CommandInfo class.

2022-03-07 05:33 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
> +
```suggestion
import java.util.*;
```

2022-03-07 05:33 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/commands/JedisCommands.java
> +    ScriptingKeyCommands, FunctionCommands, CommandCommands {
```suggestion
    ScriptingKeyCommands, FunctionCommands {
```

2022-03-07 05:33 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +
```suggestion
```

2022-03-07 05:33 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/UnifiedJedis.java
> +
```suggestion
```

2022-03-08 08:59 UTC, Avital-Fine commented on src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
> +
?

2022-03-08 09:09 UTC, Avital-Fine commented on src/main/java/redis/clients/jedis/commands/JedisCommands.java
> +    ScriptingKeyCommands, FunctionCommands, CommandCommands {
why?

2022-03-08 11:29 UTC, sazzad16 requested changes

2022-03-08 11:29 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/params/CommandListFilterByParams.java
> +    }
Add and `else` block and throw JedisException.

2022-03-08 11:29 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/CommandObjects.java
> +
Do these in Jedis.
```suggestion
```

2022-03-09 05:12 UTC, sazzad16 approved these changes

2022-03-09 05:13 UTC, merged