added dialect
redis/jedis pull request #2960
Opened 2022-03-29 18:41 UTC by DvirDukhan

2022-03-30 06:00 UTC, chayim submitted a review, later dismissed

2022-03-30 16:39 UTC, sazzad16 requested changes

2022-03-30 16:39 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/modules/search/SearchTest.java
> +        .dialect(2);
If this is not necessary to pass the test, please remove this change.

2022-03-30 16:39 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/modules/search/SearchTest.java
>      Document doc1 = client.ftSearch(index, query).getDocuments().get(0);
If this is not necessary to pass the test, please remove this change.

2022-03-30 16:39 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/modules/search/SearchTest.java
> +    Query query =  new Query("@numval:[$min $max]").addParam("min", 1).addParam("max", 2).dialect(2);
If this is not necessary to pass the test, please remove this change.
If you want to have this test as well, just add a new one.

2022-03-30 16:39 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/modules/search/SearchTest.java
> +      assertEquals("OK", client.ftConfigSet("DEFAULT_DIALECT", "3"));
Remove assert.

2022-03-30 16:39 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/modules/search/SearchTest.java
> +      assertEquals("OK", client.ftConfigSet("DEFAULT_DIALECT", "0"));
Remove assert.

2022-03-30 16:39 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/modules/search/SearchTest.java
> +    assertEquals(new HashMap<String, String>() {{
Use Collections.singletonMap(...)

2022-03-30 16:39 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/modules/search/SearchTest.java
> +    assertEquals(new HashMap<String, String>() {{
Use Collections.singletonMap(...)

2022-03-31 06:17 UTC, sazzad16 approved these changes

2022-03-31 06:23 UTC, merged