Support RESET command (#2952)
redis/jedis pull request #3015
Opened 2022-06-04 05:18 UTC by ihaohong

2022-06-05 10:47 UTC, sazzad16 requested changes
```
Error:  Tests run: 51, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.279 s <<< FAILURE! - in redis.clients.jedis.commands.jedis.AllKindOfValuesCommandsTest
Error:  reset(redis.clients.jedis.commands.jedis.AllKindOfValuesCommandsTest)  Time elapsed: 0.001 s  <<< ERROR!
redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.commands.jedis.AllKindOfValuesCommandsTest.reset(AllKindOfValuesCommandsTest.java:1142)
```

2022-06-14 15:11 UTC, ihaohong commented
Hi, I fixed the unit test failure, and run it in my workflow: https://github.com/ihaohong/jedis/runs/6883129332?check_suite_focus=true, please review again, thanks.

2022-06-17 07:28 UTC, ihaohong commented
Hi, what else need me to do for this pull request?

2022-06-17 11:57 UTC, sazzad16 commented
@ihaohong Nothing ATM. Thank you for your patience.

2022-10-23 14:17 UTC, zeekling requested changes

2022-10-23 14:17 UTC, zeekling commented on src/main/java/redis/clients/jedis/Jedis.java
> +    return connection.getStatusCodeReply();
Is login state reseted in client side.

2023-11-02 10:12 UTC, sazzad16 approved these changes

2023-11-02 11:14 UTC, yangbodong22011 approved these changes

2023-11-02 11:46 UTC, merged

2023-11-02 11:48 UTC, sazzad16 commented
@ihaohong Apologies for late and thanks for your contribution!