Update ISSUE_TEMPLATE to avoid general questions
redis/jedis pull request #3028
Opened 2022-06-16 10:03 UTC by sazzad16

2022-06-16 10:10 UTC, chayim commented on .github/ISSUE_TEMPLATE
> +Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis)
```
Discussions belong in the [Jedis Google Group](https://groups.google.com/g/jedis_redis) 
or [Jedis Github Discussions](https://github.com/redis/jedis/discussions). Discussions that belong in Google groups will be summarily closed.
```

2022-06-16 10:10 UTC, chayim requested changes
Thoughts?

2022-06-16 10:25 UTC, sazzad16 commented on .github/ISSUE_TEMPLATE
> +Everything else belongs in the [Jedis Google Group](https://groups.google.com/g/jedis_redis)
I prefer what we already have.

2022-06-19 12:31 UTC, chayim submitted a review, later dismissed

2022-06-19 12:35 UTC, sazzad16 commented on .github/ISSUE_TEMPLATE
> +Github issues SHOULD BE USED to report bugs and for DETAILED feature requests.
```suggestion
Github issues should be used to report bugs and for detailed feature requests. 
```

2022-06-19 12:36 UTC, chayim approved these changes

2022-06-19 12:36 UTC, merged