Allow exclusion of JSON dependenies
redis/jedis pull request #3223
Opened 2022-12-06 09:29 UTC by agavrilov76

Move creation of the GSON instance to a separate class which is initialized only when any of the JSON methods are being used. This allows `gson` and `org.json` transitive Maven dependencies to be excluded for the applications which don't use JSON methods.

See #2961 and  #2962 for more information and rationale

2022-12-07 09:53 UTC, sazzad16 requested changes
This PR addresses only Gson. Please update title and description accordingly.

2022-12-07 10:32 UTC, agavrilov76 commented
> This PR addresses only Gson. Please update title and description accordingly.

Done. The title and description are updated

2022-12-13 09:52 UTC, chayim approved these changes

2022-12-13 10:39 UTC, sazzad16 approved these changes

2022-12-13 10:41 UTC, merged