feat: migration from old new Long constructor
redis/jedis pull request #3289
Opened 2023-02-08 16:11 UTC by SoulPancake

2023-02-08 16:21 UTC, sazzad16 requested changes
There are more instances of new Long. Please find and replace those.

Moreover, there are few commented codes in PipeliningTest. Please change those as well.

2023-02-08 16:24 UTC, SoulPancake commented
@sazzad16 Oh, So I should modify the commented ones as well?
I was under the impression that it wouldn't matter.

2023-02-08 16:31 UTC, SoulPancake commented
> There are more instances of new Long. Please find and replace those.
> 
> Moreover, there are few commented codes in PipeliningTest. Please change those as well.

I've made the above changes and re-requested for review.

2023-02-08 16:40 UTC, sazzad16 requested changes
![image](https://user-images.githubusercontent.com/7600764/217594110-2bd9cec2-86ba-4b02-8f2f-cd210a4da043.png)

2023-02-08 17:59 UTC, SoulPancake commented on src/test/java/redis/clients/jedis/commands/jedis/ObjectCommandsTest.java
> +    assertEquals(Long.valueOf(1), refcount);
@sazzad16 As you can see I have made those changes as well

2023-02-08 17:59 UTC, SoulPancake commented on src/test/java/redis/clients/jedis/commands/jedis/PublishSubscribeCommandsTest.java
> +          assertEquals(Long.valueOf(2l), numPatterns);
@sazzad16 Reference :

2023-02-10 05:33 UTC, SoulPancake commented
@sazzad16 Did you get a chance to review this?

2023-02-10 16:53 UTC, sazzad16 approved these changes

2023-02-10 16:55 UTC, merged