Fix binary value in comment
redis/jedis pull request #3402
Opened 2023-05-09 04:02 UTC by vector090

When first setting "0" to redis, the bits are actually 0011, instead of number 0 with bits 0000.

( And the first setpos(3, true) makes 0011 instead of 0001, and so forth )

2023-05-09 04:05 UTC, vector090 commented
For convenience, I've also written some code to print bits, which makes bit navigation easier.
e.g. The final bits are:

    /*
0011 0001  0000 0100  0000 0000  0000 0000  0000 0001  
0123 4567  8901 2345  6789 0123  4567 8901  2345 6789  
     */

2023-05-09 09:12 UTC, sazzad16 requested changes
Same state and comment is also present in following `bitposBinary()` test method.

Again, both of these tests are available in src/test/java/redis/clients/jedis/commands/unified/BitCommandsTestBase.java as well.

@vector090 Could you please change in all of these places? 3 more places to be exact.

2023-05-10 10:22 UTC, vector090 commented
> Same state and comment is also present in following `bitposBinary()` test method.
> 
> Again, both of these tests are available in src/test/java/redis/clients/jedis/commands/unified/BitCommandsTestBase.java as well.
> 
> @vector090 Could you please change in all of these places? 3 more places to be exact.

WIP

2023-05-10 13:11 UTC, sazzad16 commented
@vector090 It seems to be the first one.

2023-05-11 01:05 UTC, vector090 commented
> @vector090 It seems to be the first one.

Code updated.
Please review.

2023-05-11 05:03 UTC, sazzad16 approved these changes

2023-05-11 05:05 UTC, merged