Fixed some typos and formatting issues across the project
redis/jedis pull request #3486
Opened 2023-07-26 15:57 UTC by sdotsenko

As commit title says, some minor typo fixes

2023-07-26 16:06 UTC, sazzad16 requested changes

2023-07-26 16:06 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/params/ZAddParams.java
> +   * Only set the key if it's already exists.
```suggestion
   * Only set the key if it already exists.
```

2023-07-27 05:07 UTC, sazzad16 approved these changes

2023-07-27 18:31 UTC, sdotsenko commented
@sazzad16, sorry, pushed the commit once again due to missed Signed-off line,

Is anybody looking into failing Integration pipeline?, looks like it's unstable for a month+

2023-08-09 06:36 UTC, sazzad16 approved these changes

2023-08-09 06:36 UTC, merged