Added functionality for 'WITHHASH' in GeoRadiusResponse
redis/jedis pull request #3538
Opened 2023-09-15 11:29 UTC by Harsh4902

- Added 'Unsigned52BitInteger' class.
- data field 'hashRawScore' added to hold value when using 'WITHHASH' parameter.
- added a test for this.

solving #3527

2023-09-16 14:08 UTC, sazzad16 requested changes

2023-09-16 14:08 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Unsigned52BitInteger.java
> +    if (value < 0 || value > 0x1FFFFFFFFFFFFFL) {
This check can be done in test(s).

2023-09-17 04:56 UTC, Harsh4902 commented on src/main/java/redis/clients/jedis/Unsigned52BitInteger.java
> +public class Unsigned52BitInteger {
Okay, will remove the 'Unsigned52BitInteger' class.

2023-09-18 15:50 UTC, Harsh4902 commented
@sazzad16 Please review the last commit.

2023-09-19 10:32 UTC, sazzad16 commented
@Harsh4902 We already have `rawScore` and won't need `hashRawScore` separately. JavaDoc will be added to clarify the confusion by #3542.

Thank you for investing your precious time in Jedis. Hopefully we'll merge some of your contributions in future.

2023-09-19 10:32 UTC, closed without merging