Create Java code snippets for sets redis#3626
redis/jedis pull request #3661
Opened 2023-12-21 20:56 UTC by suraj11chauhan

I have added the Java code example for the 'set' operation in the 'io.redis.examples' package. Please review my code! set_tutorial#3626 @sav-norem

2023-12-22 21:15 UTC, dwdougherty requested changes
Thanks for re-submitting, Suraj.

The code is missing a couple of STEP_END lines, which breaks the doc build. Please correct per the comments below.

2023-12-22 21:15 UTC, dwdougherty commented on src/test/java/io/redis/examples/SetsExample.java
> +        // REMOVE_END
```suggestion
        // REMOVE_END
        // STEP_END
```

2023-12-22 21:15 UTC, dwdougherty commented on src/test/java/io/redis/examples/SetsExample.java
> +        // REMOVE_END
```suggestion
        // REMOVE_END
        // STEP_END
```

2023-12-23 06:14 UTC, suraj11chauhan commented
I have added '// STEP_END' lines to the code. Thank you!! @dwdougherty

2024-01-02 15:13 UTC, dwdougherty approved these changes
LGTM. Docs build correctly.

2024-01-02 15:55 UTC, merged