Enrich the information returned by toString() of Connection
redis/jedis pull request #3745
Opened 2024-02-28 02:09 UTC by jjz921024

Currently, the information returned by `tostring()` of connection is very poor. we can refer the info format of netty channel to represent a connection 

https://github.com/netty/netty/blob/3c65eae052b7f460e054e6ce765cfba7f433ea32/transport/src/main/java/io/netty/channel/AbstractChannel.java#L382-L419

2024-02-28 07:32 UTC, sazzad16 commented
Note: Due to unique id, existing usages like `aConnection.toString(otherConnection.toString())` will fail.

2024-08-08 09:53 UTC, jjz921024 commented
> Note: Due to unique id, existing usages like `aConnection.toString(otherConnection.toString())` will fail.

@sazzad16 Hi, Thanks for pointing out that this will bring breaking change. For compatibility, can we add two new method that provides `remoteAddr` and `localAddr` for user and keep `toString` method. 

I think the address info of `connection` is very useful for user at debug.

2024-08-08 15:31 UTC, sazzad16 commented
@jjz921024 

> Hi, Thanks for pointing out that this will bring breaking change. For compatibility, can we add two new method that provides `remoteAddr` and `localAddr` for user and keep `toString` method.

That's possible.

You can also put all the necessary information into a single String, just without overriding toString(). This is something I started in #3137 due to #3058 but didn't move forward because of lack of traction.

2024-08-09 03:29 UTC, jjz921024 commented
I have updated for this feature. Add two new `getRemoteHostAndPort()` and `getLocalHostAndPort()` method at connection.
When socket is connected, they will return remote and local address info respectively.  @sazzad16 please review, thank.

2024-08-11 14:07 UTC, sazzad16 commented
@jjz921024 Apologies for the dilemma. I prefer your earlier implementation. WDYT about bringing it back; with renaming `toString()` to something like `toIdentityString()`.

2024-08-12 08:16 UTC, jjz921024 commented
> @jjz921024 Apologies for the dilemma. I prefer your earlier implementation. WDYT about bringing it back; with renaming `toString()` to something else (like `toIdentityString()`).

That's fine. I had reverted the last commit. Please review.

2024-08-12 08:57 UTC, sazzad16 requested changes

2024-08-12 08:57 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Connection.java
> +  public String toIdentityString() {
Keep the existing one.
```suggestion
  @Override
  public String toString() {
    return "Connection{" + socketFactory + "}";
  }

  public String toIdentityString() {
```

2024-08-12 09:02 UTC, sazzad16 requested changes

2024-08-12 09:02 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Connection.java
> +    return strVal;
Include the class name using `getClass()`.

2024-08-12 09:11 UTC, jjz921024 commented on src/main/java/redis/clients/jedis/Connection.java
> +  public String toIdentityString() {
Ohhh.... Sorry about it. My mistake.

2024-08-12 10:27 UTC, jjz921024 commented
@sazzad16 Hi, I found there are a NullPointException when invoke `toIdentityString` before connection is connected and had fixed  it. Please review.

2024-08-12 11:41 UTC, sazzad16 requested changes
LGTM!
Please add unit test. At least a simple one.

2024-08-12 12:12 UTC, jjz921024 commented
> LGTM! Please add unit test. At least a simple one.

@sazzad16 I had added a test case. Please review.  :)

2024-08-12 15:25 UTC, sazzad16 approved these changes

2024-08-12 15:26 UTC, merged