Add support for configuring connection pool to MultiClusterPooledConnectionProvider
redis/jedis pull request #3801
Opened 2024-04-05 15:50 UTC by thachlp

Issue: https://github.com/redis/jedis/issues/3753

2024-04-06 06:34 UTC, thachlp commented on src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
> +            connectionPoolConfig = new ConnectionPoolConfig();
Should we add a default ConnectionPoolConfig?

2024-04-17 05:21 UTC, sazzad16 requested changes
Apologies. I reviewed this some time ago. Just now I've realized I never _submitted_ it.

2024-04-17 11:15 UTC, thachlp commented on src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
> +                            config.getJedisClientConfig(), poolConfig), retry, circuitBreaker));
Nice, I updated

2024-04-17 11:23 UTC, sazzad16 requested changes

2024-04-17 11:23 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
> +                             ConnectionPoolConfig connectionPoolConfig) {
```suggestion
                             GenericObjectPoolConfig<Connection> connectionPoolConfig) {
```

2024-04-17 11:23 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProviderTest.java
> +        }
```suggestion
        try (MultiClusterPooledConnectionProvider customProvider = new MultiClusterPooledConnectionProvider(new MultiClusterClientConfig.Builder(clusterConfigs).build())) {
            MultiClusterPooledConnectionProvider.Cluster activeCluster = customProvider.getCluster();
            ConnectionPool connectionPool = activeCluster.getConnectionPool();
            assertEquals(8, connectionPool.getMaxTotal());
            assertEquals(4, connectionPool.getMaxIdle());
            assertEquals(1, connectionPool.getMinIdle());
        }
```

2024-04-18 07:53 UTC, sazzad16 approved these changes

2024-04-18 07:53 UTC, merged

2024-04-18 10:51 UTC, sazzad16 commented
Merged.

Thanks @thachlp for your contribution.

2024-04-18 14:01 UTC, thachlp commented
Thanks @sazzad16