StreamEntry support Binary instead of String
redis/jedis pull request #3803
Opened 2024-04-06 09:10 UTC by thachlp

Issue: https://github.com/redis/jedis/issues/3566

2024-04-06 09:49 UTC, sazzad16 requested changes
We must not break the existing implementations.

2024-04-06 15:26 UTC, thachlp commented
> We must not break the existing implementations.

Hi, @sazzad16, thanks for the review 🙇
How do we resolve this issue?

2024-04-06 15:34 UTC, sazzad16 commented
> How do we resolve this issue?

By creating new methods.

---

I just realized what your title says:

> StreamEntry support Binary instead of String

Actually we want StreamEntry binary support while keeping the String ones.

2024-04-06 16:22 UTC, thachlp commented
> > How do we resolve this issue?
> 
> By creating new methods.
> 
> I just realized what your title says:
> 
> > StreamEntry support Binary instead of String
> 
> Actually we want StreamEntry binary support while keeping the String ones.

Thanks, I will update.

2024-04-18 09:53 UTC, thachlp reviewed
Hi @sazzad16, as I understand, there is xadd support `Map<byte[], byte[]> hash` already.
```
  public final CommandObject<byte[]> xadd(byte[] key, XAddParams params, Map<byte[], byte[]> hash) {
    return new CommandObject<>(addFlatMapArgs(commandArguments(XADD).key(key).addParams(params), hash),
        BuilderFactory.BINARY);
  }
```

2024-07-21 12:24 UTC, jfloodnet commented
Now that this package supports binary value in stream entries, would someone be able to update spark redis to support binary columns also?

It is currently only Map<string, string> https://github.com/RedisLabs/spark-redis/blob/master/src/main/scala/com/redislabs/provider/redis/streaming/RedisStreamReceiver.scala#L108

Which causes the following error:

`java.lang.ClassCastException: class org.apache.spark.unsafe.types.UTF8String cannot be cast to class [B (org.apache.spark.unsafe.types.UTF8String is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap')
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getBinary(rows.scala:46)`

If your stream entry schema has binary data:

```    
    public static StructType redisSchema() {
        return new StructType(new StructField[]{
                DataTypes.createStructField("msg", DataTypes.StringType, true)
        });
    }
```

2024-07-25 05:48 UTC, sazzad16 commented
@jfloodnet This PR is closed by OP without being merged.

2024-07-25 08:04 UTC, jfloodnet commented
> @jfloodnet This PR is closed by OP without being merged.

oh that's true. @thachlp what was the reason you closed this PR?

2024-07-26 03:03 UTC, thachlp commented
@jfloodnet I am just ambiguous about doing it, but If it is important, I will continue on it now, I will ask @sazzad16 for help.

2025-04-08 00:22 UTC, closed without merging