Support IGNORE argument in TimeSeries commands
redis/jedis pull request #3830
Opened 2024-05-05 10:35 UTC by sazzad16

2024-05-20 07:50 UTC, tishun commented on src/test/java/redis/clients/jedis/modules/timeseries/TimeSeriesTest.java
> +    //System.out.println(client.tsInfo("series-ignore").getProperties()); // doesn't provide IGNORE info
NIT: Perhaps not need to submit this?

2024-06-05 11:56 UTC, uglide requested changes

2024-06-05 11:56 UTC, uglide commented on src/main/java/redis/clients/jedis/timeseries/RedisTimeSeriesCommands.java
> +   * {@code TS.ADD key timestamp value
TS.INCRBY and TS.DECRBY should also be updated

2024-06-07 11:02 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/timeseries/RedisTimeSeriesCommands.java
>    long tsAdd(String key, long timestamp, double value);
Yes

2024-06-07 11:12 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/timeseries/TSAlterParams.java
> +  private boolean ignore;
See comment below.

2024-06-07 12:42 UTC, tishun commented on src/main/java/redis/clients/jedis/timeseries/TSAlterParams.java
> +    this.ignoreMaxTimediff = maxTimediff;
Fair. Thanks

2024-06-14 04:56 UTC, sazzad16 commented
Resolved by #3860

2024-06-14 04:56 UTC, closed without merging