Avoid racing conditions as per design
redis/jedis pull request #3920
Opened 2024-08-14 15:18 UTC by tishun

2024-08-25 11:29 UTC, sazzad16 requested changes

2024-08-25 11:29 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/csc/CacheConnection.java
> +      cacheEntry = CacheEntry.newCacheEntry(cacheKey, this, value);
I don't this is properly doing:

> If the correct dummy entry is still there, replace it with the actual value.

The correct dummy entry is the one we used in previous `clientSideCache.set(cacheKey, cacheEntry);` but current `cacheEntry` is not guaranteed to be that one.
Furthermore, it has to be ensured to replace THAT one.

2024-08-26 13:55 UTC, tishun commented
Hey folks, after talking to @atakavci today I believe this is not really needed.

@sazzad16 apologies for wasting your time reviewing this PR.

2024-08-26 13:55 UTC, closed without merging

2024-08-27 10:36 UTC, sazzad16 commented
@tishun No problem at all.