Add javadoc to clear up implicit behavior
redis/jedis pull request #3991
Opened 2024-10-09 22:39 UTC by joshrotenberg

This should probably be fixed with some kind of configuration merging, but in an effort to avoid breaking changes, these docs should at least make the behavior clear.

Fixes #3982.

2024-10-10 05:03 UTC, sazzad16 requested changes
@joshrotenberg Thank you for this PR. Suggested some changes, please address. You can your own words in sentences.

2024-10-10 05:03 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/Jedis.java
> +   * the JedisClientConfig object, the URI values will take precedence.
```suggestion
   * the JedisClientConfig object, the URI values will take precedence even if they are absent in URI.
```

2024-10-10 05:03 UTC, sazzad16 commented on src/main/java/redis/clients/jedis/UnifiedJedis.java
> +   * the JedisClientConfig object, the URI values will take precedence.
```suggestion
   * the JedisClientConfig object, the URI values will take precedence even if they are absent in URI.
```

2024-10-10 19:16 UTC, joshrotenberg commented on src/main/java/redis/clients/jedis/Jedis.java
> +   * For example, if the URI is "redis://user:password@localhost:6379/1", the user and password fields will be set
Not sure what you're wanting changed here. That extra colon is wrong ... did you want the SSL scheme in the URI (`rediss`)

2024-10-10 19:24 UTC, joshrotenberg commented
I made a few changes, let me know what you think.

2024-10-12 04:59 UTC, sazzad16 approved these changes

2024-10-13 05:15 UTC, merged